// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { productCatalog } from "npm:@/data/products";
var CATEGORIES = ["quartz", "silica-gel", "precipitated", "fumed", "advanced-series"];
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List all silica products in the SiLiCA catalog. Optionally filter by category (quartz, silica-gel, precipitated, fumed, advanced-series).",
  inputSchema: {
    category: z.enum(CATEGORIES).optional().describe("Optional product category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = productCatalog.filter((p) => !category || (p.category ?? "quartz") === category).map((p) => ({
      slug: p.slug,
      name: p.name,
      enName: p.enName,
      jaName: p.jaName,
      category: p.category ?? "quartz",
      tagline: p.tagline,
      enTagline: p.enTagline,
      isCategoryIndex: !!p.isCategoryIndex,
      parentSlug: p.parentSlug
    }));
    return {
      content: [{ type: "text", text: `${items.length} product(s) found.` }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { productCatalog as productCatalog2 } from "npm:@/data/products";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch the full detail of a SiLiCA product by its slug \u2014 includes descriptions (KO/EN/JA), features, specifications, applications, and sub-models.",
  inputSchema: {
    slug: z2.string().min(1).describe("Product slug, e.g. 'fused-silica-a-grade'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const p = productCatalog2.find((x) => x.slug === slug);
    if (!p) {
      return {
        content: [{ type: "text", text: `Product not found: ${slug}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `${p.name} (${p.enName})

${p.description}`
        }
      ],
      structuredContent: { product: p }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { productCatalog as productCatalog3 } from "npm:@/data/products";
var search_products_default = defineTool3({
  name: "search_products",
  title: "Search products",
  description: "Full-text search across the SiLiCA catalog \u2014 matches product name (KO/EN/JA), tagline, description, applications, and slug.",
  inputSchema: {
    query: z3.string().min(1).describe("Free-text search term."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase();
    const matches = productCatalog3.filter((p) => {
      const haystack = [
        p.slug,
        p.name,
        p.enName,
        p.jaName ?? "",
        p.tagline,
        p.enTagline ?? "",
        p.description,
        p.enDescription ?? "",
        ...p.applications ?? []
      ].join(" \n ").toLowerCase();
      return haystack.includes(q);
    }).slice(0, limit).map((p) => ({
      slug: p.slug,
      name: p.name,
      enName: p.enName,
      category: p.category ?? "quartz",
      tagline: p.tagline
    }));
    return {
      content: [{ type: "text", text: `${matches.length} match(es) for "${query}".` }],
      structuredContent: { count: matches.length, matches }
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
import { productCatalog as productCatalog4 } from "npm:@/data/products";
var list_applications_default = defineTool4({
  name: "list_applications",
  title: "List applications for a product",
  description: "Return the industrial application list for a specific SiLiCA product by slug.",
  inputSchema: {
    slug: z4.string().min(1).describe("Product slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const p = productCatalog4.find((x) => x.slug === slug);
    if (!p) {
      return {
        content: [{ type: "text", text: `Product not found: ${slug}` }],
        isError: true
      };
    }
    return {
      content: [
        { type: "text", text: (p.applications ?? []).join("\n- ") || "No applications listed." }
      ],
      structuredContent: { slug: p.slug, applications: p.applications ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "silica-catalog-mcp",
  title: "SiLiCA Product Catalog MCP",
  version: "0.1.0",
  instructions: "Tools for exploring the SiLiCA silica product catalog: fused silica, quartz sand, silica gel, precipitated silica, fumed silica, and related grades. Use `list_products` to browse (optionally by category), `search_products` for keyword search, `get_product` for full details by slug, and `list_applications` for the industrial-use list of a product.",
  tools: [list_products_default, get_product_default, search_products_default, list_applications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
